### ISSUE TITLE
build rom error

### ISSUE THREAD

**Issue by wukaicheng** [thesprintster/kernel_realme_RMX1971#1]
Every time I compile ROM, there will be errors here, and there is no error prompt. What should I do
`make[1]: Leaving directory '/root/rr/out/target/product/RMX1971CN/obj/KERNEL_OBJ'
make: Leaving directory '/root/rr/kernel/realme/RMX1971CN'
[ 13% 94/714] Building Kernel09:58:30 ninja failed with: signal: killed

#### failed to build some targets (01:21 (mm:ss)) ####

`

kernel:https://github.com/thesprintster/kernel_realme_RMX1971

device:https://github.com/AndroidBlobs/device_realme_RMX1971CN

vendor:https://github.com/AndroidBlobs/vendor_realme_RMX1971CN

_I_ am build for RealmeQ

**Comment by thesprintster** [comment]
those are **dummy** device & vendor tree, dont use them to build rom's
